name: Create GitHub Release

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update even if versions match'
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Check pydantic-ai version
        id: check_version
        run: |
          # Clone pydantic-ai repo
          git clone https://github.com/pydantic/pydantic-ai.git /tmp/pydantic-ai
          
          # Get the latest version of pydantic-ai
          cd /tmp/pydantic-ai
          if [ -f "pyproject.toml" ]; then
            PYDANTIC_VERSION=$(grep -o 'version = "[^"]*"' pyproject.toml | head -1 | cut -d'"' -f2)
            echo "Found version in pyproject.toml: $PYDANTIC_VERSION"
          elif [ -f "setup.py" ]; then
            PYDANTIC_VERSION=$(grep -o 'version="[^"]*"' setup.py | head -1 | cut -d'"' -f2)
            echo "Found version in setup.py: $PYDANTIC_VERSION"
          else
            PYDANTIC_VERSION="0.1.0"
            echo "No version file found, using default: $PYDANTIC_VERSION"
          fi
          
          if [ -z "$PYDANTIC_VERSION" ]; then
            PYDANTIC_VERSION="0.1.0"
            echo "Failed to extract version, using default: $PYDANTIC_VERSION"
          fi
          
          # Export the version to outputs
          echo "version=$PYDANTIC_VERSION" >> $GITHUB_OUTPUT
          
          # Check if there's already a release with this version
          cd $GITHUB_WORKSPACE
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.force_update }}" == "true" ]]; then
            echo "Force update requested, will create release regardless of version"
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "release_tag=v$PYDANTIC_VERSION" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
            echo "Tag push detected, will create release"
            echo "should_build=true" >> $GITHUB_OUTPUT
            # Extract tag name without the refs/tags/ prefix
            TAG_NAME=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
            echo "release_tag=$TAG_NAME" >> $GITHUB_OUTPUT
          else
            # Check if this version already exists as a release
            EXISTING_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases | grep -o "\"tag_name\":\"v$PYDANTIC_VERSION\"" || echo "")
            if [[ -z "$EXISTING_RELEASE" ]]; then
              echo "No existing release for v$PYDANTIC_VERSION found, will create release"
              echo "should_build=true" >> $GITHUB_OUTPUT
              echo "release_tag=v$PYDANTIC_VERSION" >> $GITHUB_OUTPUT
            else
              echo "Release for v$PYDANTIC_VERSION already exists, skipping"
              echo "should_build=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Install dependencies
        if: steps.check_version.outputs.should_build == 'true'
        run: npm ci

      - name: Get pydantic-ai docs
        if: steps.check_version.outputs.should_build == 'true'
        run: |
          # Create .docs directory
          mkdir -p .docs/raw .docs/organized/code-examples .docs/organized/changelogs
          
          # Copy docs into the .docs/raw directory
          if [ -d "/tmp/pydantic-ai/docs" ]; then
            cp -r /tmp/pydantic-ai/docs/* .docs/raw/
            echo "✅ Documentation copied successfully"
          else
            echo "⚠️ No docs directory found in pydantic-ai repository"
            echo "sample-content" > .docs/raw/sample.md
          fi
          
          # Create sample example if examples directory exists
          if [ -d "/tmp/pydantic-ai/examples" ]; then
            for example_dir in /tmp/pydantic-ai/examples/*; do
              if [ -d "$example_dir" ]; then
                example_name=$(basename "$example_dir")
                example_file=".docs/organized/code-examples/$example_name.md"
                echo "# $example_name" > "$example_file"
                
                find "$example_dir" -name "*.py" | while read -r py_file; do
                  rel_path=$(realpath --relative-to="$example_dir" "$py_file")
                  echo "## $rel_path" >> "$example_file"
                  echo '```python' >> "$example_file"
                  cat "$py_file" >> "$example_file"
                  echo '```' >> "$example_file"
                  echo "" >> "$example_file"
                done
              fi
            done
            echo "✅ Examples processed successfully"
          else
            echo "⚠️ No examples directory found in pydantic-ai repository"
            echo "# Sample Example" > .docs/organized/code-examples/sample.md
          fi
          
          # Extract changelog from pydantic-ai
          if [ -f "/tmp/pydantic-ai/CHANGELOG.md" ]; then
            cp /tmp/pydantic-ai/CHANGELOG.md .docs/organized/changelogs/pydantic-ai.md
          else
            # Create a placeholder changelog if none exists
            echo "# Changelog" > .docs/organized/changelogs/pydantic-ai.md
            echo "## v${{ steps.check_version.outputs.version }}" >> .docs/organized/changelogs/pydantic-ai.md
            echo "- Initial release" >> .docs/organized/changelogs/pydantic-ai.md
          fi

      - name: Build package
        if: steps.check_version.outputs.should_build == 'true'
        run: npm run build

      - name: Create package
        if: steps.check_version.outputs.should_build == 'true'
        run: |
          # Package the server with npm pack
          npm pack
          echo "PACKAGE_FILE=$(ls pydantic-ai-docs-server-*.tgz)" >> $GITHUB_ENV

      - name: Create Git Tag
        if: steps.check_version.outputs.should_build == 'true' && github.event_name != 'push'
        run: |
          # Skip if we're processing a tag push
          TAG_NAME="${{ steps.check_version.outputs.release_tag }}"
          
          # Check if tag already exists
          if git tag | grep -q "$TAG_NAME"; then
            echo "Tag $TAG_NAME already exists locally"
          else
            # Create the tag
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          fi
          
          # Try to push the tag (will fail silently if it already exists remotely)
          git push origin "$TAG_NAME" || echo "Tag may already exist remotely"

      - name: Create GitHub Release
        if: steps.check_version.outputs.should_build == 'true'
        uses: softprops/action-gh-release@v1
        with:
          name: "pydantic-ai v${{ steps.check_version.outputs.version }}"
          tag_name: ${{ steps.check_version.outputs.release_tag }}
          files: ${{ env.PACKAGE_FILE }}
          generate_release_notes: true
          fail_on_unmatched_files: false
          body: |
            ## Pre-built Package with Documentation for pydantic-ai v${{ steps.check_version.outputs.version }}
            
            This package includes all pydantic-ai documentation for version ${{ steps.check_version.outputs.version }}.
            
            ### Usage in Cursor
            
            Add to your `.cursor/mcp.json`:
            ```json
            {
              "mcpServers": {
                "pydantic-ai": {
                  "command": "npx",
                  "args": ["-y", "github:brickfrog/pydantic-ai-docs-server"]
                }
              }
            }
            ``` 